name: wengine
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  google_fonts: ^0.3.5
  flutter_custom_clippers: ^1.1.0
  responsive_builder: ^0.3.0
  flutter_treeview: ^0.6.0+1
  shared_preferences_web: ^0.1.2+7
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  http: ^0.12.2
  event_hub: ^0.1.1
  equatable: ^1.2.5
  file_picker: ^2.1.5+1
  url_launcher: ^5.7.10
  flutter_typeahead: ^2.0.0
  badges: ^1.1.6
  responsive_image: ^0.1.0
  cached_network_image: ^2.5.0
  universal_html: ^1.2.4
  universal_io: ^1.0.2
  clipboard: ^0.1.2+8
  marquee: ^1.7.0
  change_app_package_name: ^0.1.2
  flutter_facebook_auth: ^2.0.2+1
  scrollable_positioned_list: ^0.1.10
  enhanced_future_builder: ^1.0.3
  flutter_phoenix: "^0.1.0"
  fl_chart: ^0.12.0
  font_awesome_flutter: ^8.11.0
  intl: ^0.16.1
  charts_flutter: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
