name: client
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  google_fonts: ^0.3.5
  flutter_custom_clippers: ^1.1.0
  responsive_builder: ^0.3.0
  flutter_treeview: ^0.6.0+1
  shared_preferences_web: ^0.1.2+7
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  http: ^0.12.2
  get_it: ^5.0.6
  streaming_shared_preferences: ^1.0.2
  event_hub: ^0.1.1
  percent_indicator: ^2.1.9
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
